
workflows:
  android-workflow:
    name: Android Build
    environment:
      groups:
        - android
      vars:
        CM_BUILD_DIR: android
      node: 18.18.0  # Node.js version is already correct
    scripts:
      - name: Install npm dependencies with specific esbuild version
        script: |
          npm install
          # Install specific esbuild version to resolve version conflict
          npm install esbuild@0.25.0 --save-exact
      - name: Install Capacitor CLI and Android platform
        script: |
          npm install @capacitor/cli @capacitor/core @capacitor/android
      - name: Build web app
        script: |
          npm run build
      - name: Add Android platform
        script: |
          npx cap add android
      - name: Sync Capacitor
        script: |
          npx cap sync
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - riyazpattan987@gmail.com
