workflows:
  android-workflow:
    name: Android Build
    environment:
      groups:
        - android
      vars:
        CM_BUILD_DIR: android
      node: 16.0.0  # Specify Node.js version for compatibility
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install Capacitor CLI and Android platform
        script: |
          npm install @capacitor/cli @capacitor/core @capacitor/android
      - name: Build web app
        script: |
          npm run build
      - name: Add Android platform
        script: |
          npx cap add android
      - name: Sync Capacitor
        script: |
          npx cap sync
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - riyazpattan987@gmail.com  # Your email for APK download link
